#!/usr/bin/env node
/**
 * tools/build.mjs — splice tsc output (dist/**\/*.js) into the inline
 * <script> block of index.html.
 *
 * Same no-build-step philosophy as vugg-simulator (this script is derived
 * from it). The shipped product (index.html) stays a single file so
 * file:// "open and play" keeps working. Source-of-truth lives under js/
 * as TypeScript "script" files (no import/export — top-level decls
 * become globals after concat).
 *
 * Naming convention: `00-`, `15-`, `20-`, … prefixes preserve load order.
 *
 * Usage:
 *   npm run build         # tsc + rebuild index.html
 *   npm run build:check   # tsc + exit 1 if rebuild would change index.html
 *
 * This script alone (without the npm wrapper) skips the tsc step and just
 * splices whatever is currently under dist/ into index.html — useful for
 * iterating on the splicer without paying tsc's compile cost each time.
 *
 * Markers in index.html:
 *   // === BUILD:bundle:start ===
 *   …concatenated content…
 *   // === BUILD:bundle:end ===
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const BUILD_DIR = join(ROOT, "dist");
const INDEX = join(ROOT, "index.html");
const START_MARKER = "// === BUILD:bundle:start ===";
const END_MARKER = "// === BUILD:bundle:end ===";

function walkSorted(dir) {
  const out = [];
  const stack = [dir];
  while (stack.length) {
    const d = stack.pop();
    let entries;
    try {
      entries = readdirSync(d).sort();
    } catch {
      continue;
    }
    for (const name of entries) {
      if (name.startsWith(".")) continue;
      const p = join(d, name);
      const st = statSync(p);
      if (st.isDirectory()) stack.push(p);
      else if (name.endsWith(".js")) out.push(p);
    }
  }
  return out.sort((a, b) =>
    relative(BUILD_DIR, a).split(sep).join("/").localeCompare(
      relative(BUILD_DIR, b).split(sep).join("/")
    )
  );
}

function concatModules(files) {
  const parts = [];
  for (const f of files) {
    const rel = relative(BUILD_DIR, f).split(sep).join("/");
    parts.push(`// ── ${rel} ──`);
    parts.push(readFileSync(f, "utf8").replace(/\s+$/, ""));
  }
  return parts.join("\n\n");
}

function rebuild(html, body) {
  const i = html.indexOf(START_MARKER);
  const j = html.indexOf(END_MARKER);
  if (i < 0 || j < 0) {
    throw new Error(
      `index.html is missing build markers. Add\n  ${START_MARKER}\n  ${END_MARKER}\ninside the <script> block.`
    );
  }
  const startLineEnd = html.indexOf("\n", i);
  const endLineStart = html.lastIndexOf("\n", j) + 1;
  return (
    html.slice(0, startLineEnd + 1) +
    "// auto-generated by `npm run build` from js/**/*.ts — edit those files, not this block\n\n" +
    body +
    "\n\n" +
    html.slice(endLineStart)
  );
}

const files = walkSorted(BUILD_DIR);
if (!files.length) {
  console.error(
    `[build] no .js files found under ${relative(ROOT, BUILD_DIR)}/ — run \`npx tsc\` first or use \`npm run build\`.`
  );
  process.exit(1);
}

const html = readFileSync(INDEX, "utf8");
const body = concatModules(files);
const next = rebuild(html, body);

if (process.argv.includes("--check")) {
  if (next !== html) {
    console.error(
      `[build] index.html is out of date — run \`npm run build\` to regenerate.\n        diff length: ${Math.abs(next.length - html.length)} chars`
    );
    process.exit(1);
  }
  console.log(`[build] index.html is up to date with ${files.length} module(s)`);
  process.exit(0);
}

writeFileSync(INDEX, next);
console.log(
  `[build] rebuilt index.html from ${files.length} module(s) (${body.length.toLocaleString()} chars)`
);
